# Generated by Django 3.0.4 on 2020-09-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0002_posts_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='meta_description',
            field=models.CharField(default=1, max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='seo_title',
            field=models.CharField(default='seo', max_length=200),
            preserve_default=False,
        ),
    ]
