# Generated by Django 3.0.4 on 2020-10-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0004_posts_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='feature_post',
            field=models.BooleanField(default=False),
        ),
    ]
